/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nivel1;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
	//LINES
    @Test public void testFirstLineWin1() {
        JogoVelha jv = new JogoVelha();
			assertFalse(jv.isVelha(new int[]{
				1,1,1,
				1,0,0,
				0,0,1})
			);
    }
    @Test public void testFirstLineWin2() {
        JogoVelha jv = new JogoVelha();
			assertFalse(jv.isVelha(new int[]{
				1,1,1,
				0,0,1,
				1,0,0})
			);
    }
    @Test public void testSecondLineWin1() {
        JogoVelha jv = new JogoVelha();
			assertFalse(jv.isVelha(new int[]{
				0,1,0,
				1,1,1,
				1,0,0})
			);
    }
    @Test public void testSecondLineWin2() {
        JogoVelha jv = new JogoVelha();
			assertFalse(jv.isVelha(new int[]{
				5,8,8,
				5,5,5,
				8,5,8})
			);
    }
    @Test public void testThirdLineWin1() {
        JogoVelha jv = new JogoVelha();
			assertFalse(jv.isVelha(new int[]{
				1,0,1,
				0,1,1,
				0,0,0})
			);
    }
    @Test public void testThirdLineWin2() {
        JogoVelha jv = new JogoVelha();
			assertFalse(jv.isVelha(new int[]{
				3,4,4,
				4,3,3,
				4,4,4})
			);
    }
	//COLUMNS
    @Test public void testFirstColumnWin1() {
        JogoVelha jv = new JogoVelha();
			assertFalse(jv.isVelha(new int[]{
				1,1,0,
				1,0,0,
				1,0,1})
			);
    }
    @Test public void testFirstColumnWin2() {
        JogoVelha jv = new JogoVelha();
			assertFalse(jv.isVelha(new int[]{
				1,1,0,
				1,0,1,
				1,0,0})
			);
    }
    @Test public void testSecondColumnWin1() {
        JogoVelha jv = new JogoVelha();
			assertFalse(jv.isVelha(new int[]{
				0,1,0,
				0,1,1,
				1,1,0})
			);
    }
    @Test public void testSecondColumnWin2() {
        JogoVelha jv = new JogoVelha();
			assertFalse(jv.isVelha(new int[]{
				8,5,8,
				5,5,8,
				8,5,5})
			);
    }
    @Test public void testThirdColumnWin1() {
        JogoVelha jv = new JogoVelha();
			assertFalse(jv.isVelha(new int[]{
				0,1,1,
				1,0,1,
				0,0,1})
			);
    }
    @Test public void testThirdColumnWin2() {
        JogoVelha jv = new JogoVelha();
			assertFalse(jv.isVelha(new int[]{
				3,4,4,
				4,3,4,
				4,3,4})
			);
    }
	
	//DRAW
    @Test public void testDraw1() {
        JogoVelha jv = new JogoVelha();
			assertTrue(jv.isVelha(new int[]{
				1,0,1,
				1,0,0,
				0,1,1})
			);
    }
    @Test public void testDraw2() {
        JogoVelha jv = new JogoVelha();
			assertTrue(jv.isVelha(new int[]{
				5,8,5,
				8,5,8,
				8,5,8})
			);
    }
    @Test public void testDraw3() {
        JogoVelha jv = new JogoVelha();
			assertTrue(jv.isVelha(new int[]{
				3,3,2,
				2,2,3,
				3,3,2})
			);
    }

}
